#!/bin/bash

# Change directories while storing chronological history of cd
# traverse directory list with up and down like a web browser

# _cd right now to traverse directories

unset dirs_history[@]

dirs_history[0]="$PWD"
dirs_history_index=0
dir_history_limit=20

_cd ()
{
    [ $dirs_history_index -eq $dir_history_limit ] && {
        one="$1"
        set "${dirs_history[@]}"
        shift
        set "$one"
    }
    dirs_history[$dirs_history_index]="$1"
    cd "$1" && ((dirs_history_index++))
}

up ()
{
    [ $dirs_history_index -gt 0 ] && {
        cd "${dirs_history[ $((dirs_history_index - 2)) ]}"
        return
    }
    return 1
}

down ()
{
    [ -n "${dirs_history[ $((dirs_history_index + 1)) ]}" ] && {
        cd "${dirs_history[ $((dirs_history_index++)) ]}"
        return
    }
    return 1
}
