#!/bin/bash

# Change directories while storing history.

alias goto='    _goto_goto'
alias drop='    _goto_drop'
alias down='    _goto_down'
alias up='      _goto_up'
alias back='    _goto_back'
alias forward=' _goto_forward'

# Access/manipulate that history.

unset _goto_dir_list[@]
_goto_dir_list[0]="$PWD"
_goto_dir_list_index=0

unset _goto_dir_history[@]
_goto_dir_history[0]="$PWD"
_goto_dir_history_index=0
_goto_dir_history_limit=20

# is the destination already in the list?
_goto_check_for_uniqueness ()
{
    for dest in "${_goto_dir_list[@]}"; do
        [ "${1%?}" == "$dest" ] && return 1  # strip newline from $1, check if in list
    done
    # not in list
    return 0
}

_goto_push_to_history ()
{
    ((_goto_dir_history_index++))
    if [ $_goto_dir_history_index -gt $_goto_dir_history_limit ]; then
        _goto_dir_history=( "${_goto_dir_history[@]:1}" )
        ((_goto_dir_history--))
    fi

    _goto_dir_history[$_goto_dir_history_index]="$1"

    if [ $_goto_dir_history_index -lt $(( ${#_goto_dir_history_index[@]} - 1 )) ]; then
        _goto_dir_history=( "${_goto_dir_history[@] : 0 : $_goto_dir_history_index - 1}" )
    fi

}

_goto_print_list ()
{
    local dest
    local string
    local count=0
    {
        echo
        for dest in "${_goto_dir_list[@]}"; do
            if [ $count -eq $_goto_dir_list_index ]; then
                #printf "\033[32m%s" "*" >&2
                printf "\033[32m" # >&2
                string="*"
            else
                #printf "\033[37m%s" " " >&2
                printf "\033[37m" # >&2
                string="-"
            fi
            printf "%s\033[0m" "$string $count:$dest"
            #printf " %s:%s\n\033[00m" "$count" "$dest" >&2
            ((count++))
        done
        echo
    } >&2
}

_goto_print_history ()
{
    local dest
    local string
    local count=0
    {
        echo
        for dest in "${_goto_dir_history[@]}"; do
            if [ $count -eq $_goto_dir_history_index ]; then
                #printf "\033[32m%s" ">" >&2
                printf "\033[32m" # >&2
                string=">" # >&2
            else
                #printf "\033[37m%s" " " >&2
                printf "\033[37m" # >&2
                string="-" # >&2
            fi
            printf "%s\033[0m" "$string $dest"
            #printf " %s %s\n\033[00m" "-" "$dest" >&2
            ((count++))
        done
        echo
    }
>&2
}

_goto_goto ()
{

    # cd to directory and add to list, OR show list, OR cd to item on list by number

    local destination

    case "$1" in
        -[[:digit:]]*)
            _goto_dir_list_index="${1:1}"
            destination="${_goto_dir_list[$_goto_dir_list_index]}"

            if [ "$(cd "$destination"; pwd)" == "$PWD" ]; then
                return
            fi

            cd "$destination"
            ;;
        "")
            pr -t -m <(_goto_print_list 2>&1) <(_goto_print_history 2>&1)
            ;;
        -)
            _goto_back
            ;;
        *)
            cd "$1" && {
                if $(_goto_check_for_uniqueness "$1"); then
                    ((_goto_dir_list_index++))
                    _goto_dir_list[$_goto_dir_list_index]="$PWD"
                fi
                _goto_push_to_history "$PWD"
            }
            ;;
    esac
}

_goto_up ()
{

    # change to previous directory on list

    local destination

    if [ $_goto_dir_list_index -gt 0 ]; then
        ((_goto_dir_list_index--))
        destination="${_goto_dir_list[$_goto_dir_list_index]}"
    else
        destination="$PWD"
    fi

    _goto_push_to_history "$destination"
    cd "$destination"
}

_goto_down ()
{

    # change to next directory on list

    local destination
    if [ $((_goto_dir_list_index + 1)) -lt "${#_goto_dir_list[@]}" ]; then
        ((_goto_dir_list_index++))
        destination="${_goto_dir_list[$_goto_dir_list_index]}"
    else
        destination="$PWD"
    fi

    _goto_push_to_history "$destination"
    cd "$destination"
}

_goto_back ()
{
    [ $_goto_dir_history_index -gt 0 ] && {
        cd "${_goto_dir_history[ $((_goto_dir_history_index--)) ]}"
        return
    }
    return 1
    # change hist index
}

_goto_forward ()
{
    [ -n "${_goto_dir_history[ $((_goto_dir_history_index + 1)) ]}" ] && {
        cd "${_goto_dir_history[ $((_goto_dir_history_index++)) ]}"
        return
    }
    return 1
}

_goto_drop ()
{

    # remove directory from list by number

    case "$1" in
        [[:digit:]])
            unset _goto_dir_list[$1]
            _goto_dir_list=( "${_goto_dir_list[@]}" )
            ((_goto_dir_list_index--))
            ;;
        *)
            unset _goto_dir_list[@]
            _goto_dir_list[0]="$PWD"
            _goto_dir_list_index=0
            ;;
    esac
}
