---
- hosts: localhost
  connection: local

  tasks:
    - name: Include defaults.
      include_vars: ../defaults/main.yml

    - name: Add line in profile to source forward_back.
      lineinfile:
        dest: "{{ bash_profile_file }}"
        line: source {{ project_directory }}/forward_back
      become: yes
